INSERT INTO Ingredient(Nom,Poids,Prix,Type) VALUES
('Aigue-marine',47,20,'Gemme'),
('Alexandrite',77,20,'Gemme'),
('Azurite',12,15,'Gemme'),
('Chrysobéryl',81,14,'Gemme'),
('Grenat rouge',17,15,'Gemme'),
('Grenat violet',91,12,'Gemme'),
('Irtios',70,13,'Gemme'),
('Ivoire',54,12,'Gemme'),
('Lapis-Lazuli',100,16,'Gemme'),
('Néphrite',58,13,'Gemme'),
('Orprase',84,12,'Gemme'),
('Péridot',55,15,'Gemme'),
('Perle dorée',28,18,'Gemme'),
('Perle noire',40,12,'Gemme'),
('Pierre de lune',80,15,'Gemme'),
('Quartz bleu',54,11,'Gemme'),
('Sardonyx',70,18,'Gemme'),
('Spinelle vert sombre',21,12,'Gemme'),
('Spodumène',12,20,'Gemme'),
('Topaze jaune d\'or',57,15,'Gemme'),
('Tourmaline blanche',96,11,'Gemme'),
('Zircon',88,13,'Gemme'),
('Amulette d\'armure naturelle',92,14,'Matériel magique'),
('Anneau du bélier',26,14,'Matériel magique'),
('Baguette de sagesse du hibou',61,20,'Matériel magique'),
('Bottes de sept lieues',96,13,'Matériel magique'),
('Écu en acier',67,11,'Matériel magique'),
('Élixir de nage',71,20,'Matériel magique'),
('Épée bâtarde',11,17,'Matériel magique'),
('Épée courte',77,12,'Matériel magique'),
('Huile de ténèbres',78,14,'Matériel magique'),
('Masse d\'armes lourde',16,18,'Matériel magique'),
('Onguent d\'intemporalité',46,13,'Matériel magique'),
('Parchemin divin',50,20,'Matériel magique'),
('Parchemin profane',82,18,'Matériel magique'),
('Potion d\'agrandissement',40,16,'Matériel magique'),
('Potion de flou',35,17,'Matériel magique'),
('Potion de grâce féline',49,11,'Matériel magique'),
('Potion de regain d\'assurance',40,16,'Matériel magique'),
('Potion de ruse du renard',42,20,'Matériel magique'),
('Potion de sagesse du hibou',71,18,'Matériel magique'),
('Urgrosh nain',76,18,'Matériel magique'),
('Antidote',40,14,'Matériel non magique'),
('Arbalète légère de maître',67,17,'Matériel non magique'),
('Arc court de maître',72,20,'Matériel non magique'),
('Armure à plaques',26,13,'Matériel non magique'),
('Armure de cuir cloutée de maître',20,12,'Matériel non magique'),
('Bâtonnet(s) fumigène(s)',98,20,'Matériel non magique'),
('Cadenas simple',14,18,'Matériel non magique'),
('Carreaux',56,10,'Matériel non magique'),
('Chemise de maille',21,11,'Matériel non magique'),
('Cimeterre de maître',67,19,'Matériel non magique'),
('Eau bénite',50,18,'Matériel non magique'),
('Ecu en acier de maître',77,20,'Matériel non magique'),
('Ecu en ébénite',63,16,'Matériel non magique'),
('Epée longue de maître',95,16,'Matériel non magique'),
('Gourdin de maître',33,14,'Matériel non magique'),
('Grande hache de maître',13,19,'Matériel non magique'),
('Hache de guerre naine de maître',66,18,'Matériel non magique'),
('Hallebarde de maître',91,16,'Matériel non magique'),
('Harnois',56,20,'Matériel non magique'),
('Menottes de qualité suppérieure',40,13,'Matériel non magique'),
('Pic de guerre léger de maître',96,16,'Matériel non magique'),
('Pierre(s) à tonnerre',97,10,'Matériel non magique'),
('Rapière de maître',29,12,'Matériel non magique'),
('Rondache en ébénite',68,17,'Matériel non magique'),
('Serpe de maître',10,19,'Matériel non magique'),
('Elixir secret',87,15,'Ingrédient secret'),
('Poudre secrète',74,10,'Ingrédient secret'),
('Minéral secret',82,12,'Ingrédient secret'),
  ('Branches de sauge maléfiques',5,3.5,'Matériel magique'),
  ('Ongles de lutin',1,13.6,'Matériel non magique'),
  ('Plumes de phoenix',0.2,428,'Matériel magique'),
  ('Cheveux de sorcière',0.5,52,'Matériel non magique');