INSERT INTO Potion(Nom,Diluant,Themperature,Prix,Inventeur) VALUES
('Huile d\'arme magique','Vin',93,474,idDeInventeur('Elias de Kelliwic\'h')),
('Huile de bénédiction d\'arme','Jus de fruit',55,799,idDeInventeur('Merlin')),
('Huile de gourdin magique','Eau',80,481,idDeInventeur('Gandalf')),
('Huile de pierre magique','Jus de fruit',67,345,idDeInventeur('Elias de Kelliwic\'h')),
('Huile de ténèbres','Eau',86,658,idDeInventeur('Severus Rogue')),
('Potion d\'agrandissement','Vin',77,975,idDeInventeur('Elias de Kelliwic\'h')),
('Potion d\'aide','Jus de fruit',86,940,NULL),
('Potion d\'alignement indétectable','Bière',78,376,idDeInventeur('Severus Rogue')),
('Potion d\'armure de mage','Jus de fruit',87,124,idDeInventeur('Panoramix')),
('Potion de bouclier de la foi','Vin',67,436,idDeInventeur('Panoramix')),
('Potion de délivrance de la paralysie','Vin',87,963,idDeInventeur('Severus Rogue')),
('Potion de détection faussée','Vin',79,525,idDeInventeur('Gandalf')),
('Potion de flou','Bière',76,440,idDeInventeur('Panoramix')),
('Potion de force de taureau','Jus de fruit',86,238,idDeInventeur('Severus Rogue')),
('Potion de grâce féline','Jus de fruit',58,149,idDeInventeur('Elias de Kelliwic\'h')),
('Potion de lévitation','Jus de fruit',86,869,idDeInventeur('Panoramix')),
('Potion de morsure magique','Jus de fruit',71,326,NULL),
('Potion de passage sans traces','Bière',83,634,idDeInventeur('Severus Rogue')),
('Potion de pattes d\'araignée','Eau',88,473,idDeInventeur('Elias Kelliwic\'h')),
('Potion de peau d\'écorce','Vin',71,236,idDeInventeur('Panoramix')),
('Potion de protection contre la loi','Vin',66,681,idDeInventeur('Severus Rogue')),
('Potion de protection contre le bien','Bière',86,210,idDeInventeur('Gandalf')),
('Potion de protection contre le chaos','Bière',86,145,idDeInventeur('Elias de Kelliwic\'h')),
('Potion de protection contre le mal','Bière',50,936,NULL),
('Potion de protection contre les projectiles','Vin',93,760,idDeInventeur('Panoramix')),
('Potion de ralentissement du poison','Vin',83,220,idDeInventeur('Gandalf')),
('Potion de rapetissement','Vin',89,533,idDeInventeur('Merlin')),
('Potion de regain d\'assurance','Jus de fruit',79,430,idDeInventeur('Panoramix')),
('Potion de résistances aux énergies destructives','Vin',81,113,idDeInventeur('Severus Rogue')),
('Potion de restauration partielle','Vin',81,805,idDeInventeur('Elias de Kelliwic\'h')),
('Potion de ruse du renard','Bière',76,716,idDeInventeur('Merlin')),
('Potion de sagesse du hibou','Jus de fruit',100,821,idDeInventeur('Severus Rogue')),
('Potion de sanctuaire','Eau',55,991,idDeInventeur('Severus Rogue')),
('Potion de saut','Bière',51,832,idDeInventeur('Panoramix')),
('Potion de soins légers','Bière',88,764,idDeInventeur('Gandalf')),
('Potion de soins modérés','Jus de fruit',69,652,idDeInventeur('Gandalf')),
('Potion de splendeur de l\'aigle','Jus de fruit',85,552,idDeInventeur('Gandalf')),
('Potion de vision dans le noir','Jus de fruit',99,436,idDeInventeur('Severus Rogue')),
('Potion d\'endurance aux énergies destructives','Vin',91,445,idDeInventeur('Gandalf')),
('Potion d\'endurance de l\'ours','Jus de fruit',68,473,idDeInventeur('Severus Rogue')),
('Potion d\'invisibilité pour les animaux','Vin',81,335,idDeInventeur('Gandalf')),
('Potion d\'invisibilité pour les morts-vivants','Bière',91,331,idDeInventeur('Elias de Kelliwic\'h')),
('Potion d\'invisibilité','Jus de fruit',77,645,idDeInventeur('Elias de Kelliwic\'h'));