INSERT INTO Potion_Ingredient(Potion,Ingredient,Unite,Quantite,Duree) VALUES
(idDePotion('Huile d\'arme magique'),idDIngredient('Sardonyx'),idDUnite('Poignée'),1,13),
(idDePotion('Huile de bénédiction d\'arme'),idDIngredient('Perle dorée'),idDUnite('Pincée'),1,12),
(idDePotion('Huile de gourdin magique'),idDIngredient('Perle dorée'),idDUnite('Poignée'),3,10),
(idDePotion('Huile de pierre magique'),idDIngredient('Sardonyx'),idDUnite('Once'),1,10),
(idDePotion('Huile de ténèbres'),idDIngredient('Quartz bleu'),idDUnite('Poignée'),3,6),
(idDePotion('Potion d\'agrandissement'),idDIngredient('Perle noire'),idDUnite('Poignée'),2,7),
(idDePotion('Potion d\'aide'),idDIngredient('Irtios'),idDUnite('Nuage'),3,6),
(idDePotion('Potion d\'alignement indétectable'),idDIngredient('Grenat rouge'),idDUnite('Poignée'),1,12),
(idDePotion('Potion d\'armure de mage'),idDIngredient('Grenat violet'),idDUnite('Pincée'),2,20),
(idDePotion('Potion de bouclier de la foi'),idDIngredient('Lapis-Lazuli'),idDUnite('Soufle'),1,6),
(idDePotion('Potion de délivrance de la paralysie'),idDIngredient('Spodumène'),idDUnite('Once'),1,16),
(idDePotion('Potion de détection faussée'),idDIngredient('Grenat violet'),idDUnite('Once'),3,23),
(idDePotion('Potion de flou'),idDIngredient('Néphrite'),idDUnite('Pincée'),1,17),
(idDePotion('Potion de force de taureau'),idDIngredient('Chrysobéryl'),idDUnite('Soufle'),3,20),
(idDePotion('Potion de grâce féline'),idDIngredient('Azurite'),idDUnite('Poignée'),1,18),
(idDePotion('Potion de lévitation'),idDIngredient('Perle dorée'),idDUnite('Poignée'),2,13),
(idDePotion('Potion de morsure magique'),idDIngredient('Topaze jaune d\'or'),idDUnite('Poignée'),3,5),
(idDePotion('Potion de passage sans traces'),idDIngredient('Aigue-marine'),idDUnite('Soufle'),1,3),
(idDePotion('Potion de pattes d\'araignée'),idDIngredient('Chrysobéryl'),idDUnite('Once'),3,0),
(idDePotion('Potion de peau d\'écorce'),idDIngredient('Grenat rouge'),idDUnite('Nuage'),2,0),
(idDePotion('Potion de protection contre la loi'),idDIngredient('Chrysobéryl'),idDUnite('Soufle'),1,25),
(idDePotion('Potion de protection contre le bien'),idDIngredient('Grenat rouge'),idDUnite('Poignée'),2,19),
(idDePotion('Potion de protection contre le chaos'),idDIngredient('Ivoire'),idDUnite('Nuage'),1,8),
(idDePotion('Potion de protection contre le mal'),idDIngredient('Perle noire'),idDUnite('Pincée'),1,20),
(idDePotion('Potion de protection contre les projectiles'),idDIngredient('Pierre de lune'),idDUnite('Soufle'),3,11),
(idDePotion('Potion de ralentissement du poison'),idDIngredient('Irtios'),idDUnite('Pincée'),3,0),
(idDePotion('Potion de rapetissement'),idDIngredient('Néphrite'),idDUnite('Nuage'),3,21),
(idDePotion('Potion de regain d\'assurance'),idDIngredient('Spodumène'),idDUnite('Poignée'),2,15),
(idDePotion('Potion de résistances aux énergies destructives'),idDIngredient('Lapis-Lazuli'),idDUnite('Once'),3,16),
(idDePotion('Potion de restauration partielle'),idDIngredient('Alexandrite'),idDUnite('Nuage'),3,0),
(idDePotion('Potion de ruse du renard'),idDIngredient('Sardonyx'),idDUnite('Pincée'),2,4),
(idDePotion('Potion de sagesse du hibou'),idDIngredient('Lapis-Lazuli'),idDUnite('Nuage'),2,12),
(idDePotion('Potion de sanctuaire'),idDIngredient('Quartz bleu'),idDUnite('Poignée'),1,18),
(idDePotion('Potion de saut'),idDIngredient('Spodumène'),idDUnite('Nuage'),3,22),
(idDePotion('Potion de soins légers'),idDIngredient('Néphrite'),idDUnite('Pincée'),2,22),
(idDePotion('Potion de soins modérés'),idDIngredient('Sardonyx'),idDUnite('Soufle'),1,13),
(idDePotion('Potion de splendeur de l\'aigle'),idDIngredient('Sardonyx'),idDUnite('Soufle'),1,11),
(idDePotion('Potion de vision dans le noir'),idDIngredient('Sardonyx'),idDUnite('Soufle'),3,25),
(idDePotion('Potion d\'endurance aux énergies destructives'),idDIngredient('Spodumène'),idDUnite('Soufle'),2,10),
(idDePotion('Potion d\'endurance de l\'ours'),idDIngredient('Alexandrite'),idDUnite('Soufle'),1,13),
(idDePotion('Potion d\'invisibilité pour les animaux'),idDIngredient('Quartz bleu'),idDUnite('Nuage'),2,20),
(idDePotion('Potion d\'invisibilité pour les morts-vivants'),idDIngredient('Perle dorée'),idDUnite('Pincée'),3,24),
(idDePotion('Potion d\'invisibilité'),idDIngredient('Perle noire'),idDUnite('Nuage'),3,23),
(idDePotion('Huile d\'arme magique'),idDIngredient('Branches de sauge maléfiques'),idDUnite('Nuage'),3,9),
(idDePotion('Huile de bénédiction d\'arme'),idDIngredient('Épée courte'),idDUnite('Once'),2,11),
(idDePotion('Huile de gourdin magique'),idDIngredient('Épée bâtarde'),idDUnite('Soufle'),3,0),
(idDePotion('Huile de pierre magique'),idDIngredient('Bottes de sept lieues'),idDUnite('Poignée'),1,8),
(idDePotion('Huile de ténèbres'),idDIngredient('Ongles de lutin'),idDUnite('Soufle'),1,14),
(idDePotion('Potion d\'agrandissement'),idDIngredient('Potion de sagesse du hibou'),idDUnite('Poignée'),1,4),
(idDePotion('Potion d\'aide'),idDIngredient('Amulette d\'armure naturelle'),idDUnite('Pincée'),1,24),
(idDePotion('Potion d\'alignement indétectable'),idDIngredient('Épée courte'),idDUnite('Nuage'),1,7),
(idDePotion('Potion d\'armure de mage'),idDIngredient('Urgrosh nain'),idDUnite('Once'),1,18),
(idDePotion('Potion de bouclier de la foi'),idDIngredient('Épée courte'),idDUnite('Pincée'),1,7),
(idDePotion('Potion de délivrance de la paralysie'),idDIngredient('Onguent d\'intemporalité'),idDUnite('Once'),3,16),
(idDePotion('Potion de détection faussée'),idDIngredient('Parchemin divin'),idDUnite('Pincée'),3,1),
(idDePotion('Potion de flou'),idDIngredient('Écu en acier'),idDUnite('Once'),2,0),
(idDePotion('Potion de force de taureau'),idDIngredient('Épée bâtarde'),idDUnite('Nuage'),2,19),
(idDePotion('Potion de grâce féline'),idDIngredient('Amulette d\'armure naturelle'),idDUnite('Poignée'),3,23),
(idDePotion('Potion de lévitation'),idDIngredient('Parchemin divin'),idDUnite('Pincée'),1,0),
(idDePotion('Potion de morsure magique'),idDIngredient('Plumes de fenix'),idDUnite('Once'),1,1),
(idDePotion('Potion de passage sans traces'),idDIngredient('Ongles de lutin'),idDUnite('Nuage'),3,11),
(idDePotion('Potion de pattes d\'araignée'),idDIngredient('Cheveux de sorcière'),idDUnite('Once'),3,15),
(idDePotion('Potion de peau d\'écorce'),idDIngredient('Épée courte'),idDUnite('Poignée'),2,18),
(idDePotion('Potion de protection contre la loi'),idDIngredient('Cheveux de sorcière'),idDUnite('Once'),3,13),
(idDePotion('Potion de protection contre le bien'),idDIngredient('Écu en acier'),idDUnite('Nuage'),1,1),
(idDePotion('Potion de protection contre le chaos'),idDIngredient('Baguette de sagesse du hibou'),idDUnite('Once'),2,23),
(idDePotion('Potion de protection contre le mal'),idDIngredient('Cheveux de sorcière'),idDUnite('Once'),2,0),
(idDePotion('Potion de protection contre les projectiles'),idDIngredient('Branches de sauge maléfiques'),idDUnite('Poignée'),1,19),
(idDePotion('Potion de ralentissement du poison'),idDIngredient('Baguette de sagesse du hibou'),idDUnite('Poignée'),3,15),
(idDePotion('Potion de rapetissement'),idDIngredient('Anneau du bélier'),idDUnite('Poignée'),2,0),
(idDePotion('Potion de regain d\'assurance'),idDIngredient('Bottes de sept lieues'),idDUnite('Pincée'),1,4),
(idDePotion('Potion de résistances aux énergies destructives'),idDIngredient('Baguette de sagesse du hibou'),idDUnite('Poignée'),3,6),
(idDePotion('Potion de restauration partielle'),idDIngredient('Amulette d\'armure naturelle'),idDUnite('Pincée'),2,0),
(idDePotion('Potion de ruse du renard'),idDIngredient('Anneau du bélier'),idDUnite('Pincée'),1,20),
(idDePotion('Potion de sagesse du hibou'),idDIngredient('Bottes de sept lieues'),idDUnite('Soufle'),3,12),
(idDePotion('Potion de sanctuaire'),idDIngredient('Amulette d\'armure naturelle'),idDUnite('Soufle'),2,9),
(idDePotion('Potion de saut'),idDIngredient('Baguette de sagesse du hibou'),idDUnite('Pincée'),3,7),
(idDePotion('Potion de soins légers'),idDIngredient('Écu en acier'),idDUnite('Nuage'),2,0),
(idDePotion('Potion de soins modérés'),idDIngredient('Cheveux de sorcière'),idDUnite('Soufle'),1,10),
(idDePotion('Potion de splendeur de l\'aigle'),idDIngredient('Masse d\'armes lourde'),idDUnite('Poignée'),2,7),
(idDePotion('Potion de vision dans le noir'),idDIngredient('Parchemin profane'),idDUnite('Nuage'),2,17),
(idDePotion('Potion d\'endurance aux énergies destructives'),idDIngredient('Élixir de nage'),idDUnite('Nuage'),3,0),
(idDePotion('Potion d\'endurance de l\'ours'),idDIngredient('Élixir de nage'),idDUnite('Soufle'),2,1),
(idDePotion('Potion d\'invisibilité pour les animaux'),idDIngredient('Urgrosh nain'),idDUnite('Soufle'),3,4),
(idDePotion('Potion d\'invisibilité pour les morts-vivants'),idDIngredient('Urgrosh nain'),idDUnite('Pincée'),3,0),
(idDePotion('Potion d\'invisibilité'),idDIngredient('Potion de sagesse du hibou'),idDUnite('Nuage'),2,21),
(idDePotion('Huile d\'arme magique'),idDIngredient('Epée longue de maître'),idDUnite('Poignée'),2,8),
(idDePotion('Huile de bénédiction d\'arme'),idDIngredient('Chemise de maille'),idDUnite('Pincée'),3,26),
(idDePotion('Huile de gourdin magique'),idDIngredient('Carreaux'),idDUnite('Pincée'),3,8),
(idDePotion('Huile de pierre magique'),idDIngredient('Arbalète légère de maître'),idDUnite('Once'),3,24),
(idDePotion('Huile de ténèbres'),idDIngredient('Harnois'),idDUnite('Soufle'),2,24),
(idDePotion('Potion d\'agrandissement'),idDIngredient('Harnois'),idDUnite('Nuage'),1,34),
(idDePotion('Potion d\'aide'),idDIngredient('Chemise de maille'),idDUnite('Pincée'),3,0),
(idDePotion('Potion d\'alignement indétectable'),idDIngredient('Arbalète légère de maître'),idDUnite('Nuage'),1,31),
(idDePotion('Potion d\'armure de mage'),idDIngredient('Hache de guerre naine de maître'),idDUnite('Nuage'),3,5),
(idDePotion('Potion de bouclier de la foi'),idDIngredient('Armure de cuir cloutée de maître'),idDUnite('Soufle'),1,26),
(idDePotion('Potion de délivrance de la paralysie'),idDIngredient('Harnois'),idDUnite('Poignée'),2,5),
(idDePotion('Potion de détection faussée'),idDIngredient('Pic de guerre léger de maître'),idDUnite('Nuage'),2,0),
(idDePotion('Potion de flou'),idDIngredient('Cadenas simple'),idDUnite('Poignée'),1,38),
(idDePotion('Potion de force de taureau'),idDIngredient('Cadenas simple'),idDUnite('Nuage'),2,0),
(idDePotion('Potion de grâce féline'),idDIngredient('Antidote'),idDUnite('Pincée'),3,37),
(idDePotion('Potion de lévitation'),idDIngredient('Armure à plaques'),idDUnite('Pincée'),1,0),
(idDePotion('Potion de morsure magique'),idDIngredient('Epée longue de maître'),idDUnite('Once'),3,4),
(idDePotion('Potion de passage sans traces'),idDIngredient('Ecu en acier de maître'),idDUnite('Pincée'),2,2),
(idDePotion('Potion de pattes d\'araignée'),idDIngredient('Hache de guerre naine de maître'),idDUnite('Pincée'),1,18),
(idDePotion('Potion de peau d\'écorce'),idDIngredient('Ecu en ébénite'),idDUnite('Pincée'),3,0),
(idDePotion('Potion de protection contre la loi'),idDIngredient('Ecu en acier de maître'),idDUnite('Poignée'),2,36),
(idDePotion('Potion de protection contre le bien'),idDIngredient('Menottes de qualité suppérieure'),idDUnite('Pincée'),1,26),
(idDePotion('Potion de protection contre le chaos'),idDIngredient('Ecu en ébénite'),idDUnite('Soufle'),1,0),
(idDePotion('Potion de protection contre le mal'),idDIngredient('Pic de guerre léger de maître'),idDUnite('Soufle'),2,18),
(idDePotion('Potion de protection contre les projectiles'),idDIngredient('Pierre(s) à tonnerre'),idDUnite('Soufle'),2,3),
(idDePotion('Potion de ralentissement du poison'),idDIngredient('Armure de cuir cloutée de maître'),idDUnite('Once'),3,24),
(idDePotion('Potion de rapetissement'),idDIngredient('Pic de guerre léger de maître'),idDUnite('Pincée'),2,41),
(idDePotion('Potion de regain d\'assurance'),idDIngredient('Hache de guerre naine de maître'),idDUnite('Pincée'),3,30),
(idDePotion('Potion de résistances aux énergies destructives'),idDIngredient('Bâtonnet(s) fumigène(s)'),idDUnite('Poignée'),1,46),
(idDePotion('Potion de restauration partielle'),idDIngredient('Gourdin de maître'),idDUnite('Nuage'),1,0),
(idDePotion('Potion de ruse du renard'),idDIngredient('Chemise de maille'),idDUnite('Pincée'),1,35),
(idDePotion('Potion de sagesse du hibou'),idDIngredient('Carreaux'),idDUnite('Pincée'),2,9),
(idDePotion('Potion de sanctuaire'),idDIngredient('Bâtonnet(s) fumigène(s)'),idDUnite('Nuage'),2,43),
(idDePotion('Potion de saut'),idDIngredient('Antidote'),idDUnite('Once'),3,4),
(idDePotion('Potion de soins légers'),idDIngredient('Grande hache de maître'),idDUnite('Soufle'),3,38),
(idDePotion('Potion de soins modérés'),idDIngredient('Serpe de maître'),idDUnite('Pincée'),1,0),
(idDePotion('Potion de splendeur de l\'aigle'),idDIngredient('Ecu en ébénite'),idDUnite('Pincée'),3,40),
(idDePotion('Potion de vision dans le noir'),idDIngredient('Arc court de maître'),idDUnite('Pincée'),1,11),
(idDePotion('Potion d\'endurance aux énergies destructives'),idDIngredient('Grande hache de maître'),idDUnite('Nuage'),2,16),
(idDePotion('Potion d\'endurance de l\'ours'),idDIngredient('Ecu en ébénite'),idDUnite('Soufle'),1,0),
(idDePotion('Potion d\'invisibilité pour les animaux'),idDIngredient('Eau bénite'),idDUnite('Soufle'),1,22),
(idDePotion('Potion d\'invisibilité pour les morts-vivants'),idDIngredient('Armure à plaques'),idDUnite('Soufle'),3,9),
(idDePotion('Potion d\'invisibilité'),idDIngredient('Epée longue de maître'),idDUnite('Poignée'),1,14),
(idDePotion('Potion de protection contre le bien'),idDIngredient('Elixir secret'),idDUnite('Poignée'),2,0),
(idDePotion('Potion de protection contre les projectiles'),idDIngredient('Poudre secrète'),idDUnite('Once'),2,18);
